name: Test

on: [push,  pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

#      - name: Build with Maven
#        run: mvn clean install

      - name: Test with Maven
        run: ./mvnw test